# Generated by Django 5.1.3 on 2025-02-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_at', models.DateTimeField(auto_now_add=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_dob', models.DateField()),
                ('patient_gender', models.CharField(max_length=50)),
                ('patient_bloodGroup', models.CharField(max_length=50)),
                ('patient_disability', models.CharField(max_length=50)),
                ('patient_contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
