# Generated by Django 5.1.3 on 2025-02-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcare', '0002_patient_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_gender',
        ),
    ]
