# Generated by Django 5.1.3 on 2025-02-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcare', '0003_remove_patient_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Select Gender', max_length=1),
        ),
    ]
