# Generated by Django 5.1.3 on 2025-02-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcare', '0005_alter_patient_patient_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_bloodGroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3),
        ),
    ]
