# Generated by Django 5.1.3 on 2025-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcare', '0006_alter_patient_patient_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10),
        ),
    ]
