# Generated by Django 5.1.3 on 2025-02-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcare', '0007_alter_patient_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('doctor_contact', models.CharField(max_length=50)),
                ('doctor_specialization', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Radiology', 'Radiology'), ('Neurology', 'Neurology'), ('Mental Health', 'Mental Health'), ('Oncology', 'Oncology'), ('Osteology', 'Osteology')], default='cardiology', max_length=50)),
                ('doctor_availability', models.CharField(choices=[('7am-1pm', '7am-1pm'), ('1pm-6pm', '1pm-6pm'), ('6pm-9pm', '6pm-9pm'), ('9pm-7am', '9pm-7am')], default='7am-1pm', max_length=50)),
            ],
        ),
    ]
