# Generated by Django 5.1.3 on 2025-03-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcare', '0010_alter_doctor_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(default='doctors/default.jpg', upload_to='doctors/'),
        ),
    ]
