# Generated by Django 5.1.3 on 2025-03-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcare', '0011_alter_doctor_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(upload_to='doctors/'),
        ),
    ]
