# Generated by Django 5.1.3 on 2025-03-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcare', '0012_alter_doctor_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_quantity', models.IntegerField()),
                ('medicine_category', models.CharField(choices=[('Antibiotics', 'Antibiotics'), ('Painkillers', 'Painkillers'), ('Antivirals', 'Antivirals'), ('Antiseptics', 'Antiseptics'), ('Vaccine', 'Vaccine'), ('Vitamin', 'Vitamin')], default='Antibiotics', max_length=50)),
                ('medicine_prescription', models.CharField(choices=[('1×3', '1×3'), ('2×3', '2×3'), ('2×2', '2×2'), ('5ml×2', '5ml×2'), ('5ml×3', '5ml×3'), ('10ml×2', '10ml×2'), ('10ml×3', '10ml×3')], default='1×3', max_length=50)),
                ('medicine_duration', models.CharField(choices=[('5 weeks', '5 weeks'), ('4 weeks', '4 weeks'), ('3 weeks', '3 weeks'), ('2 weeks', '2 weeks'), ('1 week', '1 week')], default='5 weeks', max_length=50)),
                ('medicine_image', models.ImageField(upload_to='medicines/')),
                ('medicine_price', models.IntegerField()),
            ],
        ),
    ]
