# Generated by Django 5.1.3 on 2025-03-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcare', '0014_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_name',
            new_name='name',
        ),
    ]
