# Generated by Django 5.1.3 on 2025-03-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcare', '0015_rename_patient_email_appointment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Virtual', 'Virtual')], default='Physical', max_length=10),
        ),
    ]
